### ISSUE TITLE
Updating a team will not let me use paramter in "pnp:Team DisplayName="{parameter:TeamTitle}"

### ISSUE THREAD

**Issue by Bjorn80** [pnp/PnP-Provisioning-Schema#573]
Im currently updating Teams with tabs.

**Works**

I can successfully update Teams when setting DisplayName = "hardcodedName" and running:
`Invoke-PnPTenantTemplate -Path "D:\temp\UpdateTeam.xml"`

I can use parameters to set teams tab names
```
$Path = "D:\temp\UpdateTeam_2.xml"
Invoke-PnPTenantTemplate -Path $Path -Parameters @{"Customer"="CoolCust1"}
```

**Doesnt Work**
However if I dare to try using a parameter on the value, DisplayName, see under:
`<pnp:Team DisplayName="{parameter:TeamTitle}" Description="" Visibility="Private" Photo="" Specialization="None">`

```
$Path = "D:\temp\UpdateTeam_3.xml"
Invoke-PnPTenantTemplate -Path $Path -Parameters @{"TeamTitle"="bjorntest6"}
```

I get the error:
```
Get-PnPException

Message          : Exception while invoking endpoint https://graph.microsoft.com/v1.0/groups.
Stacktrace       :    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy       
                   hierarchy, String sequenceId, ApplyConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 2
```

**Top of XML**
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema">
  <pnp:Preferences Author="John Black" Version="1.0" Generator="Human being :-)">
    <pnp:Parameters>
      <pnp:Parameter Key="TeamTitle">bjorntest2</pnp:Parameter>
    </pnp:Parameters>
  </pnp:Preferences>
 <pnp:Teams>
    <pnp:Team DisplayName="{parameter:TeamTitle}" Description="" Visibility="Private" Photo="" Specialization="None">
      <pnp:FunSettings />

**PowerShell and PnP**
```
PS D:\ITPRO> Get-Module pnp.powershell


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.8.0      PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAzureADGroupMember...}


PS D:\ITPRO> get-host



Name             : Visual Studio Code Host
Version          : 2021.10.2
InstanceId       : 5317331f-6269-497f-b6b9-f07b389a11a0
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

Any ideas why I cant set displayName with parameters?

brgs

Bjørn

**Comment by Bjorn80** [comment]
Typically,

I found that copying the syntax for setting the DisplayName from the site
https://www.collabmagazine.com/provisioning-teams-in-microsoft-teams-using-the-pnp-provisioning-engine/
actually solved my issue. So this case kan be closed.

The error was som kind of syntax error in setting and using the parameter for the DisplayName.

brgs

Bjørn
